import React, { useEffect, useState, createContext, useContext, useRef } from 'react';
import './Notification.css';
import { v4 as uuidv4 } from 'uuid'; // Import the UUID library to generate unique keys

// Context for managing notifications
const NotificationContext = createContext();

// Hook to use notifications anywhere in the app
export const useNotification = () => useContext(NotificationContext);

const NotificationProvider = ({ children }) => {
  const [notifications, setNotifications] = useState([]);
  const MAX_NOTIFICATIONS = 3; // Limit to 3 notifications at a time

  // Active notifications tracker
  const activeNotifications = useRef(new Set()); // Use a Set to track active messages

  // Function to add a new notification
  const showNotification = (message, type = 'success') => {
    // Check if the same message and type already exist in active notifications
    const messageKey = `${type}:${message}`;
    if (activeNotifications.current.has(messageKey)) return; // Prevent adding duplicate notifications

    activeNotifications.current.add(messageKey); // Mark this message as active
    const id = uuidv4(); // Generate a unique ID using uuid

    const newNotification = { id, message, type, timestamp: Date.now() };

    setNotifications((prevNotifications) => {
      let updatedNotifications = [...prevNotifications, newNotification];

      // Ensure we only keep the maximum number of notifications
      if (updatedNotifications.length > MAX_NOTIFICATIONS) {
        updatedNotifications = updatedNotifications.slice(-MAX_NOTIFICATIONS);
      }

      // Store in sessionStorage
      sessionStorage.setItem('notifications', JSON.stringify(updatedNotifications));
      return updatedNotifications;
    });

    // Remove the notification from active set after a delay (4 seconds)
    setTimeout(() => {
      activeNotifications.current.delete(messageKey);
    }, 4000);
  };

  // Function to remove a notification by ID
  const removeNotification = (id) => {
    setNotifications((prevNotifications) => {
      const updatedNotifications = prevNotifications.filter((notification) => notification.id !== id);

      // Update sessionStorage
      sessionStorage.setItem('notifications', JSON.stringify(updatedNotifications));
      return updatedNotifications;
    });
  };

  // Function to get pending notifications from sessionStorage
  const getPendingNotifications = () => {
    return JSON.parse(sessionStorage.getItem('notifications')) || [];
  };

  // Function to clean up expired notifications (4 seconds)
  const cleanUpExpiredNotifications = () => {
    setNotifications((prevNotifications) => {
      const now = Date.now();
      const updatedNotifications = prevNotifications.filter((notification) => now - notification.timestamp < 4000);

      // Update sessionStorage
      sessionStorage.setItem('notifications', JSON.stringify(updatedNotifications));
      return updatedNotifications;
    });
  };

  // Check for stored notifications on mount and periodically clean up expired notifications
  useEffect(() => {
    const storedNotifications = getPendingNotifications();
    setNotifications(storedNotifications);

    const intervalId = setInterval(() => {
      cleanUpExpiredNotifications(); // Clean up expired notifications every 1 second
    }, 1000);

    return () => clearInterval(intervalId);
  }, []);

  return (
    <NotificationContext.Provider value={{ showNotification }}>
      {children}
      <div className="matrix-toast-container">
        {notifications.map((notification) => (
          <Notification
            key={notification.id} // Ensure the key is based on the unique id generated by uuid
            message={notification.message}
            type={notification.type}
            onClose={() => removeNotification(notification.id)}
          />
        ))}
      </div>
    </NotificationContext.Provider>
  );
};

const Notification = ({ message, type, onClose }) => {
  useEffect(() => {
    const timer = setTimeout(() => {
      onClose();
    }, 4000); // Notification disappears after 4 seconds

    return () => clearTimeout(timer); // Cleanup timer on component unmount
  }, [onClose]);

  return (
    <div className={`matrix-custom-toast-notification matrix-custom-toast-notification-${type}`}>
      {message}
    </div>
  );
};

export { NotificationProvider };
